.TH DHCP-STATS 1 "October 28 2023" "version 1.0" "User Manual"
.SH NAME
dhcp-stats \- A tool for monitoring and collecting statistics about DHCP traffic.
.SH SYNOPSIS
.B dhcp-stats
[ \-r
.I filename
] [ \-i
.I interface-name
] \fIip-prefix\fR [ \fIip-prefix\fR ... ]
.SH DESCRIPTION
\fBdhcp-stats\fR is a tool for monitoring and running Dynamic Host Configuration Protocol (DHCP).
It allows the user to get clear information regarding network IP addresses by entering network prefixes.
.PP
The output displays for each specified IP address the maximum number of devices that can connect, the current number of connected devices, and the network occupancy percentage (calculated using the maximum number of devices and the current occupancy).
Statistics can be made from a file or from actual network traffic.
.PP
The tool alerts the user whenever a device connects that causes prefix saturation to be greater than 50% (even when the saturation goes from eg. 55% to 63%).
All of the saturation alerts are also written to syslog.
.SH OPTIONS
.TP
.BR \-r " " \fIfilename\fR
Specifies the name of the pcap file from which data will be read and statistics generated and output to the terminal using the ncurses library.
If omitted, then at least the \fB-i\fR option must be used for \fBdhcp-stats\fR to run.
.TP
.BR \-i " " \fIinterface-name\fR
Specifies the name of the network interface (for example, ens33) to be monitored.
If omitted, then at least the \fB-r\fR option must be used for \fBdhcp-stats\fR to run.
.TP
\fIip-prefix\fR
Mandatory argument specifying the IP address with its prefix to be monitored.
The format of the address must be written as \fB<IP address>/<IP prefix>\fR (for example 192.168.1.1/24, where 192.168.1.1 is the IP address and 24 is the prefix).
One or more IP addresses with their prefixes can be specified.
These IP addresses must be separated by spaces.
.SH PŘÍKLADY
.PP
Spustit \fBdhcp-stats\fR pro monitorování defaultního síťového rozhraní a záznam dat do souboru \fIoutput.log\fR:
.nf
\fB
./dhcp-stats -r output.log 192.168.1.0
\fR
.fi
.PP
Spustit \fBdhcp-stats\fR na specifickém síťovém rozhraní \fBeth0\fR a monitorování více IP prefixů:
.nf
\fB
./dhcp-stats -i eth0 192.168.1.0 192.168.2.0
\fR
.fi
.SH CHYBY
Jakékoliv známé chyby a problémy by měly být hlášeny na odpovídajícím fóru nebo trackeru chyb projektu.
.SH AUTOR
Tato stránka manuálu byla vytvořena [vaše jméno], pro [název vaší organizace nebo odkaz na projekt].
.SH VIDEJTE TAKÉ
\fBdhcp\fR(5), \fBsyslog\fR(3), \fBnetworkmanager\fR(8)