.TH DHCP-STATS 1 "October 28 2023" "version 1.0" "User Manual"
.SH NAME
dhcp-stats \- A tool for monitoring and collecting statistics about DHCP traffic.
.SH SYNOPSIS
.B dhcp-stats
[ \-r
.I filename
] [ \-i
.I interface-name
] \fIip-prefix\fR [ \fIip-prefix\fR ... ]
.SH DESCRIPTION
\fBdhcp-stats\fR is a tool for monitoring and running Dynamic Host Configuration Protocol (DHCP).
It allows the user to get clear information regarding network IP addresses by entering network prefixes.
.PP
The output displays for each specified IP address the maximum number of devices that can connect, the current number of connected devices, and the network occupancy percentage (calculated using the maximum number of devices and the current occupancy).
Statistics can be made from a file or from actual network traffic.
.PP
The tool alerts the user whenever a device connects that causes prefix saturation to be greater than 50% (even when the saturation goes from eg. 55% to 63%).
All of the saturation alerts are also written to syslog.
.SH OPTIONS
.TP
.BR \-r " " \fIfilename\fR
Specifies the name of the pcap file from which data will be read and statistics generated and output to the terminal using the ncurses library.
If omitted, then at least the \fB-i\fR option must be used for \fBdhcp-stats\fR to run.
In combination with \fB-i\fR, program will process the given pcap file first and it will then listen to DHCP communication using chosen interface (in the \fB-i\fR option) in realtime.
.TP
.BR \-i " " \fIinterface-name\fR
Specifies the name of the network interface (for example, ens33) to be monitored.
If omitted, then at least the \fB-r\fR option must be used for \fBdhcp-stats\fR to run.
In combination with \fB-r\fR, program will process the given pcap file first and it will then listen to DHCP communication using chosen interface (in the \fB-i\fR option) in realtime.
.TP
\fIip-prefix\fR
Mandatory argument specifying the IP address with its prefix to be monitored.
The format of the address must be written as \fB<IP address>/<IP prefix>\fR (for example 192.168.1.1/24, where 192.168.1.1 is the IP address and 24 is the prefix).
One or more IP addresses with their prefixes can be specified.
These IP addresses must be separated by spaces.
.SH EXAMPLES
.PP
Run dhcp-stats to realtime monitor the ens33 network interface (\fB-i\fR used):
.nf
\fB
sudo ./dhcp-stats -i ens33 192.168.1.1/24
\fR
.PP
Run dhcp-stats to generate statistics from the myComm.pcap file using the addresses 10.1.101.1/24, 10.1.6.1/24 and 192.168.1.1/24 (\fB-r\fR used):
.nf
\fB
sudo ./dhcp-stats -r myComm.pcap 10.1.101.1/24 10.1.6.1/24 192.168.1.1/24
\fR
.fi
.PP
Running dhcp-stats using the myComm.pcap file and subsequent realtime monitoring of communication with the ens33 network interface at addresses 10.1.101.1/24, 10.1.6.1/24 and 192.168.1.1/24 (\fB-i\fR and \fB-r\fR used):
.nf
\fB
sudo ./dhcp-stats -i ens33 -r myComm.pcap 10.1.101.1/24 10.1.6.1/24 192.168.1.1/24
\fR
.fi
.SH AUTHOR
This manpage was created by Ondřej Lukášek (xlukas15) as part of a project for the ISA (Network Applications and Network Administration) course for the year 2023.
.SH SEE ALSO
\fBdhcp\fR(5), \fBsyslog\fR(3), \fBnetworkmanager\fR(8)